[workspace]
resolver = "2"
members = [
    "packages/web",
    "packages/calculations",
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }

# workspace
calculations = { path = "packages/calculations" }
