[package]
name = "warframe"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
calculations = { workspace = true }
bon =  { workspace = true }
rootcause = { workspace = true }
tap = { workspace = true }

[features]
default = ["web"]
web = ["dioxus/web"]
server = ["dioxus/server"]
